### ISSUE TITLE
BiomeE segmentation fault

### ISSUE THREAD

**Issue by stineb** [geco-bern/rsofun#204] opened 2024-02-08 13:11 UTC
Continuous integration tests for BiomeE runs on Ubuntu sometimes throw an error (see for example [here](https://github.com/geco-bern/rsofun/actions/runs/7827490816/job/21355408200)):
```
   *** caught segfault ***
  address 0x559f7bf30070, cause 'memory not mapped'
  Segmentation fault (core dumped)
```

This happens even after removing zero-indexed variables.

We should use additional gfortran compiler flags to catch problems at the stage of compilation. To be checked are the ones described on [this post](https://scicomp.stackexchange.com/questions/36045/ifort-everithing-ok-but-with-gfortran-segmentation-fault).

**Comment by stineb** [comment] 2024-02-08 14:02
For testing, additional compiler flags can be added in `Makevars.in` (on Linux and Mac) and in `Makevars.win` (on Windows). For example, this is to be added at the top of the file:

```
PKG_FFLAGS = -fbounds-check
```

**Comment by stineb** [comment] 2024-02-09 15:51
Vova also got errors from CRAN for his r3PG package. They are related to memory allocation, which vaguely relates to our BiomeE problem. 
See [here](https://github.com/trotsiuk/r3PG/issues/37).
This may be another potential lead...

**Comment by stineb** [comment] 2024-04-26 12:37
- [ ] Resolve compiler warnings for compilation with fags `-frecursive -fbounds-check -Wall -Wextra -Wpedantic`
- [ ] Valgrind checks, follow [this](https://github.com/trotsiuk/r3PG/issues/37)

**Comment by marcadella** [comment] 2024-09-17 07:13
Ideas of what the problem could be:
1. Shared library mismatch: we compile with a set of libraries and run on a platform with a different set of libraries (different versions) (see [here](https://stackoverflow.com/questions/49190251/caught-segfault-memory-not-mapped-error-in-r)). It could also happen if some cache prevents recompiling some parts of the code (typically the C layer).
1. A bug in the C layer corrupting the memory (see [here](https://stat.ethz.ch/pipermail/r-help/2008-October/175885.html)).

(2.) can definitely explain the intermittent character of the bug. It is harder to explain it with (1.) also not impossible in case where a call to a shared library is not do in some cases.

**Comment by stineb** [comment] 2024-09-17 09:00
To cut out parts of the code, may disable P-model photosynthesis. Looking at files:

- `gpp_biomee.mod.f90`, disable option `trim(myinterface%params_siml%method_photosynth) == "pmodel"`
- `photosynth_pmodel.mod.f90`

**Comment by marcadella** [comment] 2024-09-23 09:06
Update:
- Compiling and running `analysis/biome_segmentation_fault.R` works fine (no segfault) on Ubuntu 24.04 with R 4.4.1 and gcc 13.2.0.
- Compiling and running `analysis/biome_segmentation_fault.R` gets segfault on Ubuntu 24204 with R 4.4.0 (and 4.3.2) and gcc 11.4.0.

The same compilation flags were used (by copying the content of R HOME's etc/Makeconf into ~/.R/Makvars). The likely cultprit is therefore a bug in gcc 11.4.0. The release notes of [gcc 12](https://gcc.gnu.org/gcc-12/changes.html) states when talking about C/Fortran integration: "numerous other bugs have been fixed, and an extensive set of new conformance test cases has been added."

This would nicely explain why the segfault suddenly appeared without change in the source code (assuming gcc has been upgraded on the computers where the segfault was observed).

Possible fixes:
- Indicating in the documentation that gcc 12 must be used, but not sure the people at CRAN will be happy about that...
- Rewriting the code so that it works with gcc 11 (by removing the C layer).

**Comment by fabern** [comment] 2024-09-23 13:57
Regarding the two possible fixes:  I would rather attempt to remove the C-layer than to require a user to use GCC 12.

- This is supported by: the fact that GCC 12 has only been released on 2022-05-06 (https://gcc.gnu.org/develop.html#timeline), I imagine it is still present on many machines. Furthermore: removing the C layer likely removes opportunities for further errors. Lastly, compiling is not an area I am very familiar with.

- On the other hand, CRAN appears to use GCC gfortran `> 12.2` (according to the output of [LWFBrook90R](https://cran.r-project.org/web/checks/check_results_LWFBrook90R.html)). So it might not necessarily be a problem that manifests. However, when issues appear they require fixing within ~30 to 50 days (see [here for LWFBrook90R](https://cran.r-project.org/web/packages/LWFBrook90R/index.html)). Quickly googling brought a number of different R packages that recently experienced compiling issues ([LightGBM](https://github.com/microsoft/LightGBM/issues/6522), [STAN](https://discourse.mc-stan.org/t/cran-note-for-package-using-stan-suggest-c-17/30247))

I think we need to first decide on this strategy, before attacking the second issue of "NA or changing output"

**Comment by marcadella** [comment] 2024-09-23 16:17
With gcc v12 and v13, I get completely random simulation outputs... I am 99% sure that there is actually an issue in Fortran (like bad pointer usage or something like that). It might well be that that was the reason for the segfault after all. No idea why later versions of gcc do not crash (but give random outputs...). So I think I'll first investigate that first.

**Comment by fabern** [comment] 2024-09-24 07:16
Sounds good. 
(I mean your strategy sounds good. Random outputs sound rather bad.)

**Comment by stineb** [comment] 2024-09-24 07:54
It will be informative how the Fortran-only version behaves for determining whether there is a problem in the Fortran code that is independent of any problem arising from the communication via C.

**Comment by stineb** [comment] 2024-09-24 08:07
If the R-Fortran interface remains a source of bugs, then it might be interesting considering [this package](https://cran.r-project.org/web/packages/dotCall64/).

**Comment by marcadella** [comment] 2024-09-25 13:00
I found one issue and it might actually explain it all. In `initialize_vegn_tile`, `proot` and `pseed` are never initialized. They take therefore random values propagating through the simulation. It might well be that this causes the segfault with older versions of the compiler (although I am not sure about that at all).

**Comment by marcadella** [comment] 2024-09-26 10:09
There some more uninitialized variables (for instance `pseed%n%n12`, `psoil_fs`, `psoil_sl`, `pmicr` both c12 and n14). I think the best strategy is if @lauramarques could go through the `initialize_vegn_tile` subroutine and check that all the attributes of `vegn_tile_type` and `cohort_type`. Please, use the branch `fix_biome_init` for adding the missing initializations.

**Comment by marcadella** [comment] 2024-09-30 13:29
Here is an updated list of missing initializations.
(??) indicates that I am unsure and more digging needs to be done.

- cohort_type
  - pseed%n%n14
  - root_length
- vegn_tile_type
  - pmicr (both c and n)

**Comment by marcadella** [comment] 2024-10-02 07:14
@stineb New initialization error: in gpp_biomee/gpp: `par_memory(layer)` is undefined when `layer` increases from 1 to 2. Should I initialize it with `par`?

**Comment by stineb** [comment] 2024-10-02 07:28
Yes, that would make sense. 
What happens here is that cohorts are arranged into canopy layers. Only the largest cohorts are in the top-canopy layer, receiving full sun light. In the second layer (`layer = 2`), the light is attenuated by leaf light absorption of layer 1. `par` accounts for this effect:
```
par = f_light(layer) * forcing%radiation * kfFEC * 1.0e-6
```
and this:
```
par_memory(layer) = dampen_variability(par, params_gpp%tau_acclim, par_memory(layer))
```
... just does a temporal dampening, given the daily varying light levels for the respective canopy layer.

**Comment by stineb** [comment] 2024-10-02 07:52
Yes. By definition this is true. PAR is photosynthetically active radiation and taken as a fraction of the *incident* (positive value) solar radiation.

**Comment by marcadella** [comment] 2024-10-02 10:12
I found the reason for why multiple consecutive runs yield slightly different outputs. In a lot of places in the code, some 'memory' variables are used. These variables persist until R is restarted. This means that on run 2, all the variables keep their value from the end of run 1. In some ways, it is as if we were continuing the simulation from run 1. I guess this is not the intended behavior. Problem: I don't know if it is possible to fix without major changes in the code...

**Comment by marcadella** [comment] 2024-10-02 10:57
@stineb should `myinterface%steering%init` be used for forcing a reset of `init` in `biosphere_annual`  (as it is done with `init_daily` for instance)?

**Comment by fabern** [comment] 2024-10-02 11:20
> I found the reason for why multiple consecutive runs yield slightly different outputs. In a lot of places in the code, some 'memory' variables are used. These variables persist until R is restarted. This means that on run 2, all the variables keep their value from the end of run 1. In some ways, it is as if we were continuing the simulation from run 1. I guess this is not the intended behavior. Problem: I don't know if it is possible to fix without major changes in the code...

Excellent find, this is likely explaining the issue I find here in pmodel as well: https://github.com/geco-bern/rsofun/issues/225

**Comment by marcadella** [comment] 2024-10-02 11:52
I pushed a fix which seems to solve the issue using the solution described above. @stineb and could you double check commit `1407503f`?

**Comment by fabern** [comment] 2024-10-08 13:54
Can we close this?

**Closed** 2024-10-08 14:28 UTC
